<div id="header" class="clearfix posRel">
	<div id='logo-holder' class="posAbs">
			<h1 class=""><a href="/"><img src="/Project/Design/1_Website/Panels/header/images/gyukakuLogo.png" alt="Starf" title="Affordable Websites"></a></h1>
	</div>
	<div id='navigation' class="fright posAbs">
		<div class="clearfix"><?= navigation::displayNavigationForPages('primary','home');?></div>
	</div>
</div>
<div class="navBar posAbs clearfix"></div>