<div id="footer" class="pVl clearfix">
	<div class="fleft clearfix">
		<p>Copyright 2013 Gyu-Kaku Japanese BBQ Restaurant.</p>
	</div>
	<div class="fright clearfix">
		<p>Follow us on:</p>
		<a href="https://www.facebook.com/GyuKakuPhilippines" target="_blank" title="Facebook" id="facebook">facebook</a>
		<a href="https://twitter.com/gyukaku_ph"  target="_blank" title="Twitter" id="twitter">twitter</a>
		<a href="http://instagram.com/gyukaku_ph"  target="_blank" title="Instagram" id="instagram">instagram</a>
	</div>
</div>